<?php

namespace BienBundle\Repository;

/**
 * acquerirRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class acquerirRepository extends \Doctrine\ORM\EntityRepository
{
}
