<?php

namespace BienBundle\Repository;

/**
 * adresseRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class adresseRepository extends \Doctrine\ORM\EntityRepository
{
    public function getAdresseWithZoneGeo()
    {
        $qb = $this
            ->createQueryBuilder('a')
            ->leftJoin('a.zoneGeo', 'zoneGeo')
            ->addSelect('zoneGeo')
        ;
        return $qb
            ->getQuery()
            ->getResult()
            ;
    }
    public function getAdresseOfAgence($id)
    {
        $qb = $this
            ->createQueryBuilder('a')
            ->leftJoin('a.agences', 'ag')
            ->where('ag.id : id')
            ->setParameter('id', $id);

        return $qb
            ->getQuery()
            ->getResult();

    }
}
