<?php

namespace BienBundle\Repository;

/**
 * agentRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class agentRepository extends \Doctrine\ORM\EntityRepository
{

    public function getAgentWithAdresse()
    {
        $qb = $this
            ->createQueryBuilder('a')
            ->leftJoin('a.adresse', 'ad')
            ->addSelect('ad');

        return $qb
            ->getQuery()
            ->getResult();

    }


    public function getAgentInAgence($id)
    {
        $qb = $this
            ->createQueryBuilder('a')
            ->Join('a.agences', 'agence')
            ->where('agence = :id')
            ->setParameter('id', $id);

        return $qb
            ->getQuery()
            ->getResult();
    }

    public function getAgentNotInAgence($id)
    {
        $qb = $this->_em->createQueryBuilder();

        $req1 = $this
            ->createQueryBuilder('a')
            ->Join('a.agences', 'agence')
            ->where('agence = :idd');

        $req2 = $qb->select('aa')
                ->from ('BienBundle:agent', 'aa')
                ->where($qb->expr()->notIn('aa', $req1->getDQL()))
                ->setParameter('idd' , $id)
                ->getQuery()
                ->getResult();

        return $req2;
    }

    public function getAgenceForAgent($id)
    {
        $qb = $this
            ->createQueryBuilder('a')
            ->Join('a.agences', 'agence')
            ->where ('a = :id')
            ->setParameter('id', $id);
        return $qb
            ->getQuery()
            ->getResult();
    }

    public function getAgentInBien($id)
    {
        $qb = $this
            ->createQueryBuilder('a')
            ->Join('a.biens', 'b')
            ->where ('b = :id')
            ->setParameter('id', $id);
        return $qb
            ->getQuery()
            ->getResult();
    }
}
