<?php

namespace BienBundle\Repository;

/**
 * commentaireRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class commentaireRepository extends \Doctrine\ORM\EntityRepository
{
    public function getCommentaireNonPublier()
    {
        $qb = $this
            ->createQueryBuilder('c')
            ->where('c.publierCom = :publier')
            ->setParameter('publier', 'Non')
            ;
        return $qb
            ->getQuery()
            ->getResult();
    }
    public function getCommentairePublier()
    {
        $qb = $this
            ->createQueryBuilder('c')
            ->where('c.publierCom = :publier')
            ->setParameter('publier', 'Oui')
        ;
        return $qb
            ->getQuery()
            ->getResult();
    }
    public function getCommentaireInBien($id)
    {
        $qb = $this
            ->createQueryBuilder('c')
            ->join('c.bien', 'b')
            ->addSelect('b')
            ->where('b.id = :id')
            ->setParameter('id', $id)
        ;
        return $qb
            ->getQuery()
            ->getResult();
    }
}