<?php

namespace BienBundle\Repository;

/**
 * couleurRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class couleurRepository extends \Doctrine\ORM\EntityRepository
{
}
