<?php

namespace BienBundle\Repository;

/**
 * detailsBienRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class detailsBienRepository extends \Doctrine\ORM\EntityRepository
{
    public function getOptionInBien($id)
    {
        $qb = $this
            ->createQueryBuilder('d')
            ->Join('d.biens', 'b')
            ->addSelect('b')
            ->where('b = :id')
            ->setParameter('id', $id);

        return $qb
            ->getQuery()
            ->getResult();
    }
}
