<?php

namespace BienBundle\Repository;

/**
 * optionBienRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class optionBienRepository extends \Doctrine\ORM\EntityRepository
{
}
