<?php

namespace BienBundle\Repository;

/**
 * possederRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class possederRepository extends \Doctrine\ORM\EntityRepository
{
}
