<?php

namespace BienBundle\Repository;

/**
 * proprietaireRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class proprietaireRepository extends \Doctrine\ORM\EntityRepository
{
    public function getProprioInBien($id)
    {
        $qb = $this
            ->createQueryBuilder('p')
            ->Join('p.biens', 'b')
            ->where ('b = :id')
            ->setParameter('id', $id);
        return $qb
            ->getQuery()
            ->getResult();
    }
}
