<?php

namespace BienBundle\Repository;

/**
 * sousCommentaireRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class sousCommentaireRepository extends \Doctrine\ORM\EntityRepository
{
}
