<?php

namespace BienBundle\Repository;

/**
 * typeBienRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class typeBienRepository extends \Doctrine\ORM\EntityRepository
{
}
