<?php

namespace BienBundle\Repository;

/**
 * zoneGeoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class zoneGeoRepository extends \Doctrine\ORM\EntityRepository
{
}
